"""Deterministic rendering of the consolidated audit report.

One Markdown document serves both audiences: it is written to
docs/AUDIT_YYYY-MM-DD.md (the single new file an audit may create) and its
body is what ChatGPT reviews. Content is templated from reconciled findings —
no LLM writes the report, so what it claims is exactly what the data says.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from .findings import Finding
from .reconcile import BUCKETS, ReconciledAudit
from .taskgen import TaskGraphProposal

_BUCKET_TITLES = {
    "confirmed_defects": "Confirmed defects",
    "security_risks": "Security / data-loss risks",
    "architectural_risks": "Architectural risks",
    "documentation_drift": "Documentation drift",
    "missing_tests": "Missing regression protection",
    "optional_improvements": "Optional improvements",
    "human_decisions": "Human decisions needed",
}


@dataclass(frozen=True)
class ValidationRun:
    command: str
    returncode: int
    tail: str


def _finding_block(finding: Finding) -> str:
    lines = [
        f"#### {finding.qualified_id} — {finding.proposed_action.splitlines()[0][:100]}",
        f"- severity **{finding.severity}**, confidence **{finding.confidence}**, "
        f"domain `{finding.domain}`",
        f"- files: {', '.join(f'`{p}`' for p in finding.affected_files)}",
    ]
    if finding.symbols:
        lines.append(f"- symbols: {', '.join(f'`{s}`' for s in finding.symbols)}")
    lines.append(f"- evidence: {finding.evidence}")
    lines.append(f"- impact: {finding.impact}")
    if finding.acceptance_criteria:
        lines.append(f"- acceptance: {'; '.join(finding.acceptance_criteria)}")
    if finding.validation_commands:
        lines.append(f"- validation: {'; '.join(finding.validation_commands)}")
    return "\n".join(lines)


def render_report(
    *,
    date: str,
    branch: str,
    head_sha: str,
    dirty_count: int,
    scope: str | None,
    feedback: str | None,
    validation_runs: list[ValidationRun],
    reconciled: ReconciledAudit,
    proposal: TaskGraphProposal,
    agent_failures: list[str],
    raw_reports_dir: str,
    covered_domains: tuple[str, ...] = (),
    all_domains: tuple[str, ...] = (),
) -> str:
    parts: list[str] = [
        f"# Repository audit — {date}",
        "",
        "Generated by the autoloop audit executor (deterministic rendering of "
        "reconciled subagent findings; raw agent reports preserved at "
        f"`{raw_reports_dir}`).",
        "",
        f"- branch: `{branch}` | HEAD: `{head_sha[:12]}` | uncommitted files: {dirty_count}",
    ]
    if scope:
        parts.append(f"- requested scope: {scope}")
    if feedback:
        parts.append(f"- revision feedback incorporated: {feedback}")
    parts.append("")

    # Coverage FIRST: a reader must not have to reach the bottom of a 100 KB
    # report to learn that a whole domain produced nothing usable.
    if all_domains:
        covered = set(covered_domains)
        missing = [d for d in all_domains if d not in covered]
        parts.append(
            f"## Domain coverage — {len(covered)}/{len(all_domains)} domains reported usable output"
        )
        if missing:
            parts.append("")
            parts.append(
                f"> **COVERAGE INCOMPLETE.** No usable findings from: "
                f"{', '.join(f'`{d}`' for d in missing)}. Anything those domains "
                "would have found is ABSENT from this report — treat their areas "
                "as unaudited, not as clean."
            )
        parts.append("")
        parts.append("| domain | usable output | findings |")
        parts.append("|---|---|---|")
        counts = {}
        for bucket in BUCKETS:
            for finding in reconciled.buckets[bucket]:
                counts[finding.domain] = counts.get(finding.domain, 0) + 1
        for domain in all_domains:
            ok = "yes" if domain in covered else "**NO**"
            parts.append(f"| `{domain}` | {ok} | {counts.get(domain, 0)} |")
        parts.append("")

    parts.append("## Validation baseline")
    if validation_runs:
        for run in validation_runs:
            status = "PASS" if run.returncode == 0 else f"FAIL (rc={run.returncode})"
            parts.append(f"- `{run.command}` — **{status}**")
            if run.tail:
                parts.append(f"  - tail: `{run.tail}`")
    else:
        parts.append("- (no validation commands configured)")
    parts.append("")

    for bucket in BUCKETS:
        findings = reconciled.buckets[bucket]
        parts.append(f"## {_BUCKET_TITLES[bucket]} ({len(findings)})")
        if not findings:
            parts.append("(none)")
        else:
            for finding in findings:
                parts.append(_finding_block(finding))
                parts.append("")
        parts.append("")

    parts.append(f"## Rejected items ({len(reconciled.rejected)})")
    if reconciled.rejected:
        for item in reconciled.rejected:
            parts.append(f"- [{item.domain}] {item.reason} — `{item.raw[:120]}`")
    else:
        parts.append("(none)")
    parts.append("")

    if reconciled.duplicates:
        parts.append(f"## Deduplicated ({len(reconciled.duplicates)})")
        for dropped, kept in reconciled.duplicates:
            parts.append(f"- `{dropped}` folded into `{kept}`")
        parts.append("")

    if agent_failures:
        parts.append("## Agent failures (coverage gaps — findings above are INCOMPLETE for these domains)")
        for failure in agent_failures:
            parts.append(f"- {failure}")
        parts.append("")

    parts.append(f"## Proposed task graph ({len(proposal.tasks)} tasks)")
    if proposal.tasks:
        parts.append("| id | P | title | depends on | parallel |")
        parts.append("|---|---|---|---|---|")
        for task in proposal.tasks:
            deps = ", ".join(task.depends_on) or "—"
            parts.append(
                f"| {task.id} | {task.priority} | {task.title} | {deps} | "
                f"{'yes' if task.parallelizable else 'no'} |"
            )
        parts.append("")
        parts.append(
            "To adopt this graph, reply with a `plan` decision containing the "
            "tasks below (edit freely — this is a proposal):"
        )
        parts.append("```json")
        parts.append(
            json.dumps([t.to_plan_dict() for t in proposal.tasks], indent=2)
        )
        parts.append("```")
    else:
        parts.append("(no tasks proposed)")
    if proposal.skipped:
        parts.append("")
        parts.append("Not promoted to tasks:")
        for finding_id, reason in proposal.skipped:
            parts.append(f"- `{finding_id}`: {reason}")
    parts.append("")
    return "\n".join(parts)
